import { Module } from '@nestjs/common';
import { MediaModule } from '@media';
import { PrismaModule } from '@database/prisma/prisma.module';
import {
  AddBatchDocumentsBatchUseCase,
  GetBatchDocumentUploadSignaturesUseCase,
  CreateDistributionNetworkUseCase,
  CreateDistributionNodeUseCase,
  InviteDistributionNodeUseCase,
  AcceptDistributionNodeInvitationUseCase,
  DeclineDistributionNodeInvitationUseCase,
  ListMyDistributionInvitationsUseCase,
  ListMyDistributionMembershipsUseCase,
  UpdateDistributionNodeStatusUseCase,
  CreateSupplyBatchUseCase,
  GetInventorySummaryUseCase,
  GetSupplyBatchDetailUseCase,
  CreateDistributionShipmentUseCase,
  DispatchDistributionShipmentUseCase,
  CreatePricingPolicyUseCase,
  ResolveWholesalePricingUseCase,
  ListSupplyBatchesUseCase,
  ListDistributionNetworksUseCase,
  ListDistributionNodesUseCase,
  ListDistributionShipmentsUseCase,
  ListPricingPoliciesByNetworkUseCase,
  CancelDistributionShipmentUseCase,
  ListBatchDocumentsUseCase,
  ReceiveDistributionShipmentUseCase,
} from './application/use-cases';
import { DistributionPricingRepository } from './infrastructure/persistence/distribution-pricing.repository';
import { DistributionPricingRpcController } from './presentation/rpc/distribution-pricing.rpc-controller';

@Module({
  imports: [PrismaModule, MediaModule],
  controllers: [DistributionPricingRpcController],
  providers: [
    DistributionPricingRepository,
    GetBatchDocumentUploadSignaturesUseCase,
    AddBatchDocumentsBatchUseCase,
    ListBatchDocumentsUseCase,
    CreateDistributionNetworkUseCase,
    ListDistributionNetworksUseCase,
    CreateDistributionNodeUseCase,
    InviteDistributionNodeUseCase,
    AcceptDistributionNodeInvitationUseCase,
    DeclineDistributionNodeInvitationUseCase,
    ListMyDistributionInvitationsUseCase,
    ListMyDistributionMembershipsUseCase,
    UpdateDistributionNodeStatusUseCase,
    CreateSupplyBatchUseCase,
    GetSupplyBatchDetailUseCase,
    GetInventorySummaryUseCase,
    ListSupplyBatchesUseCase,
    CreateDistributionShipmentUseCase,
    DispatchDistributionShipmentUseCase,
    ListDistributionNodesUseCase,
    ListDistributionShipmentsUseCase,
    CancelDistributionShipmentUseCase,
    ReceiveDistributionShipmentUseCase,
    CreatePricingPolicyUseCase,
    ResolveWholesalePricingUseCase,
    ListPricingPoliciesByNetworkUseCase,
  ],
  exports: [
    DistributionPricingRepository,
    GetBatchDocumentUploadSignaturesUseCase,
    AddBatchDocumentsBatchUseCase,
    ListBatchDocumentsUseCase,
    CreateDistributionNetworkUseCase,
    ListDistributionNetworksUseCase,
    CreateDistributionNodeUseCase,
    InviteDistributionNodeUseCase,
    AcceptDistributionNodeInvitationUseCase,
    DeclineDistributionNodeInvitationUseCase,
    ListMyDistributionInvitationsUseCase,
    ListMyDistributionMembershipsUseCase,
    UpdateDistributionNodeStatusUseCase,
    CreateSupplyBatchUseCase,
    GetSupplyBatchDetailUseCase,
    GetInventorySummaryUseCase,
    ListSupplyBatchesUseCase,
    CreateDistributionShipmentUseCase,
    DispatchDistributionShipmentUseCase,
    ListDistributionNodesUseCase,
    ListDistributionShipmentsUseCase,
    CancelDistributionShipmentUseCase,
    ReceiveDistributionShipmentUseCase,
    CreatePricingPolicyUseCase,
    ResolveWholesalePricingUseCase,
    ListPricingPoliciesByNetworkUseCase,
  ],
})
export class DistributionModule {}
