import { Module } from '@nestjs/common';
import { ClientsModule, Transport } from '@nestjs/microservices';
import { ConfigModule, ConfigService } from '@nestjs/config';
import { PrismaModule } from '@database/prisma/prisma.module';
import { MediaModule } from '@media';
import { OrderInventoryPort, WholesalePricingPort } from './application/ports';
import {
  OrderInventoryService,
  OrderPlacementService,
  OrderReversalService,
  PayOSPaymentService,
  ShippingCarrierAdapterService,
} from './application/services';
import {
  AddDisputeEvidenceBatchUseCase,
  AddCartItemUseCase,
  AssignAdminDisputeUseCase,
  BookOrderShippingUseCase,
  CheckoutCartUseCase,
  CreateOrderUseCase,
  CheckoutCartItemUseCase,
  QuoteCartShippingOptionsUseCase,
  QuoteCartItemShippingOptionsUseCase,
  ListGhnShippingLocationsUseCase,
  GetAdminDisputeDetailUseCase,
  GetAdminOpenDisputeCountUseCase,
  GetAdminDisputeSummaryUseCase,
  GetActiveCartUseCase,
  GetOrderByIdUseCase,
  GetOrderFulfillmentAuditUseCase,
  GetDisputeEvidenceUploadSignaturesUseCase,
  ListAdminOpenDisputesUseCase,
  ListAdminOrdersUseCase,
  GetAdminFinanceReconciliationUseCase,
  ListDisputeEvidenceUseCase,
  ListMyOrdersUseCase,
  ListSellerShopOrdersUseCase,
  GetSellerShopDashboardAnalyticsUseCase,
  GetSellerShopSummaryMetricsUseCase,
  GetSellerShopOrderStatusSummaryUseCase,
  MarkOrderPaidUseCase,
  HandlePayOSWebhookUseCase,
  ReceiveWholesaleOrderInventoryUseCase,
  RetryPayOSPaymentUseCase,
  SyncOrderShippingStatusUseCase,
  RemoveCartItemUseCase,
  CompleteOrderUseCase,
  CancelOrderUseCase,
  CalculateRiskScoreUseCase,
  CreateReportUseCase,
  ListAdminRiskScoresUseCase,
  ListAdminModerationCasesUseCase,
  ListAdminReportsUseCase,
  ListMyReportsUseCase,
  OpenOrderDisputeUseCase,
  ResolveAdminDisputeUseCase,
  ResolveOrderDisputeUseCase,
  RefundOrderUseCase,
  RecalculateRiskTargetsUseCase,
  UpdateAdminReportUseCase,
  UpdateAdminModerationCaseUseCase,
  UpdateCartItemUseCase,
  UpdateAdminDisputeCaseUseCase,
  UpdateOrderFulfillmentUseCase,
} from './application/use-cases';
import { CatalogWholesalePricingAdapter, LocalOrderInventoryAdapter, LocalWholesalePricingAdapter } from './infrastructure/adapters';
import { OrdersRepository } from './infrastructure/persistence/orders.repository';
import { OrdersRpcController } from './presentation/rpc/orders.rpc-controller';
import { CATALOG_SERVICE_CLIENT } from '@contracts';

@Module({
  imports: [
    ConfigModule,
    PrismaModule,
    MediaModule,
    ClientsModule.registerAsync([
      {
        name: CATALOG_SERVICE_CLIENT,
        imports: [ConfigModule],
        inject: [ConfigService],
        useFactory: (configService: ConfigService) => ({
          transport: Transport.TCP,
          options: {
            host:
              configService.get<string>('CATALOG_SERVICE_HOST')?.trim() ||
              configService.get<string>('USERS_SERVICE_HOST')?.trim() ||
              '127.0.0.1',
            port: configService.get<number>('CATALOG_SERVICE_PORT') ?? configService.get<number>('USERS_SERVICE_PORT') ?? 4002,
          },
        }),
      },
    ]),
  ],
  controllers: [OrdersRpcController],
  providers: [
    OrdersRepository,
    {
      provide: OrderInventoryPort,
      useClass: LocalOrderInventoryAdapter,
    },
    {
      provide: WholesalePricingPort,
      inject: [ConfigService, LocalWholesalePricingAdapter, CatalogWholesalePricingAdapter],
      useFactory: (
        configService: ConfigService,
        localAdapter: LocalWholesalePricingAdapter,
        catalogAdapter: CatalogWholesalePricingAdapter,
      ) => {
        const mode = configService.get<string>('ORDERS_PRICING_ADAPTER')?.trim().toLowerCase() || 'local';
        return mode === 'catalog' ? catalogAdapter : localAdapter;
      },
    },
    OrderInventoryService,
    OrderPlacementService,
    OrderReversalService,
    PayOSPaymentService,
    ShippingCarrierAdapterService,
    LocalWholesalePricingAdapter,
    CatalogWholesalePricingAdapter,
    GetActiveCartUseCase,
    AddCartItemUseCase,
    UpdateCartItemUseCase,
    RemoveCartItemUseCase,
    CheckoutCartUseCase,
    CheckoutCartItemUseCase,
    QuoteCartShippingOptionsUseCase,
    QuoteCartItemShippingOptionsUseCase,
    AddDisputeEvidenceBatchUseCase,
    AssignAdminDisputeUseCase,
    CreateOrderUseCase,
    ListMyOrdersUseCase,
    ListSellerShopOrdersUseCase,
    GetSellerShopDashboardAnalyticsUseCase,
    GetSellerShopSummaryMetricsUseCase,
    GetSellerShopOrderStatusSummaryUseCase,
    GetAdminDisputeDetailUseCase,
    GetAdminOpenDisputeCountUseCase,
    GetAdminDisputeSummaryUseCase,
    GetOrderByIdUseCase,
    GetOrderFulfillmentAuditUseCase,
    GetDisputeEvidenceUploadSignaturesUseCase,
    ListAdminOpenDisputesUseCase,
    ListAdminOrdersUseCase,
    GetAdminFinanceReconciliationUseCase,
    ListDisputeEvidenceUseCase,
    MarkOrderPaidUseCase,
    HandlePayOSWebhookUseCase,
    ReceiveWholesaleOrderInventoryUseCase,
    BookOrderShippingUseCase,
    SyncOrderShippingStatusUseCase,
    ListGhnShippingLocationsUseCase,
    RetryPayOSPaymentUseCase,
    CompleteOrderUseCase,
    CancelOrderUseCase,
    CalculateRiskScoreUseCase,
    CreateReportUseCase,
    ListAdminRiskScoresUseCase,
    ListAdminModerationCasesUseCase,
    ListAdminReportsUseCase,
    ListMyReportsUseCase,
    OpenOrderDisputeUseCase,
    ResolveAdminDisputeUseCase,
    ResolveOrderDisputeUseCase,
    RefundOrderUseCase,
    RecalculateRiskTargetsUseCase,
    UpdateAdminReportUseCase,
    UpdateAdminModerationCaseUseCase,
    UpdateAdminDisputeCaseUseCase,
    UpdateOrderFulfillmentUseCase,
  ],
  exports: [
    OrdersRepository,
    OrderInventoryPort,
    WholesalePricingPort,
    OrderInventoryService,
    OrderPlacementService,
    OrderReversalService,
    PayOSPaymentService,
    ShippingCarrierAdapterService,
    GetActiveCartUseCase,
    AddCartItemUseCase,
    UpdateCartItemUseCase,
    RemoveCartItemUseCase,
    CheckoutCartUseCase,
    CheckoutCartItemUseCase,
    QuoteCartShippingOptionsUseCase,
    QuoteCartItemShippingOptionsUseCase,
    AddDisputeEvidenceBatchUseCase,
    AssignAdminDisputeUseCase,
    CreateOrderUseCase,
    ListMyOrdersUseCase,
    ListSellerShopOrdersUseCase,
    GetAdminDisputeDetailUseCase,
    GetAdminOpenDisputeCountUseCase,
    GetAdminDisputeSummaryUseCase,
    GetOrderByIdUseCase,
    GetOrderFulfillmentAuditUseCase,
    GetDisputeEvidenceUploadSignaturesUseCase,
    ListAdminOpenDisputesUseCase,
    ListAdminOrdersUseCase,
    GetAdminFinanceReconciliationUseCase,
    ListDisputeEvidenceUseCase,
    MarkOrderPaidUseCase,
    HandlePayOSWebhookUseCase,
    ReceiveWholesaleOrderInventoryUseCase,
    BookOrderShippingUseCase,
    SyncOrderShippingStatusUseCase,
    ListGhnShippingLocationsUseCase,
    RetryPayOSPaymentUseCase,
    CompleteOrderUseCase,
    CancelOrderUseCase,
    CalculateRiskScoreUseCase,
    CreateReportUseCase,
    ListAdminRiskScoresUseCase,
    ListAdminModerationCasesUseCase,
    ListAdminReportsUseCase,
    ListMyReportsUseCase,
    OpenOrderDisputeUseCase,
    ResolveAdminDisputeUseCase,
    ResolveOrderDisputeUseCase,
    RefundOrderUseCase,
    RecalculateRiskTargetsUseCase,
    UpdateAdminReportUseCase,
    UpdateAdminModerationCaseUseCase,
    UpdateAdminDisputeCaseUseCase,
    UpdateOrderFulfillmentUseCase,
  ],
})
export class OrdersModule {}
