import { Module } from '@nestjs/common';
import { PrismaModule } from '@database/prisma/prisma.module';
import { MediaModule } from '@media';
import {
  AddDisputeEvidenceBatchUseCase,
  AssignAdminDisputeUseCase,
  CreateRetailOrderUseCase,
  CreateWholesaleOrderUseCase,
  GetAdminDisputeDetailUseCase,
  GetAdminOpenDisputeCountUseCase,
  GetAdminDisputeSummaryUseCase,
  GetOrderByIdUseCase,
  GetDisputeEvidenceUploadSignaturesUseCase,
  ListAdminOpenDisputesUseCase,
  ListDisputeEvidenceUseCase,
  MarkOrderPaidUseCase,
  CompleteOrderUseCase,
  CancelOrderUseCase,
  OpenOrderDisputeUseCase,
  ResolveAdminDisputeUseCase,
  ResolveOrderDisputeUseCase,
  RefundOrderUseCase,
  UpdateAdminDisputeCaseUseCase,
} from './application/use-cases';
import { OrdersRepository } from './infrastructure/persistence/orders.repository';
import { OrdersRpcController } from './presentation/rpc/orders.rpc-controller';

@Module({
  imports: [PrismaModule, MediaModule],
  controllers: [OrdersRpcController],
  providers: [
    OrdersRepository,
    AddDisputeEvidenceBatchUseCase,
    AssignAdminDisputeUseCase,
    CreateRetailOrderUseCase,
    CreateWholesaleOrderUseCase,
    GetAdminDisputeDetailUseCase,
    GetAdminOpenDisputeCountUseCase,
    GetAdminDisputeSummaryUseCase,
    GetOrderByIdUseCase,
    GetDisputeEvidenceUploadSignaturesUseCase,
    ListAdminOpenDisputesUseCase,
    ListDisputeEvidenceUseCase,
    MarkOrderPaidUseCase,
    CompleteOrderUseCase,
    CancelOrderUseCase,
    OpenOrderDisputeUseCase,
    ResolveAdminDisputeUseCase,
    ResolveOrderDisputeUseCase,
    RefundOrderUseCase,
    UpdateAdminDisputeCaseUseCase,
  ],
  exports: [
    OrdersRepository,
    AddDisputeEvidenceBatchUseCase,
    AssignAdminDisputeUseCase,
    CreateRetailOrderUseCase,
    CreateWholesaleOrderUseCase,
    GetAdminDisputeDetailUseCase,
    GetAdminOpenDisputeCountUseCase,
    GetAdminDisputeSummaryUseCase,
    GetOrderByIdUseCase,
    GetDisputeEvidenceUploadSignaturesUseCase,
    ListAdminOpenDisputesUseCase,
    ListDisputeEvidenceUseCase,
    MarkOrderPaidUseCase,
    CompleteOrderUseCase,
    CancelOrderUseCase,
    OpenOrderDisputeUseCase,
    ResolveAdminDisputeUseCase,
    ResolveOrderDisputeUseCase,
    RefundOrderUseCase,
    UpdateAdminDisputeCaseUseCase,
  ],
})
export class OrdersModule {}
