import { Module } from '@nestjs/common';
import { PrismaModule } from '@database/prisma/prisma.module';
import { MediaModule } from '@media';
import {
  AllocateOfferBatchesUseCase,
  AddOfferDocumentsBatchUseCase,
  AddOfferMediaBatchUseCase,
  CreateBrandUseCase,
  CreateCategoryUseCase,
  CreateOfferUseCase,
  CreateProductModelUseCase,
  GetOfferDocumentUploadSignaturesUseCase,
  GetOfferByIdUseCase,
  GetOfferMediaUploadSignaturesUseCase,
  GetProductModelByIdUseCase,
  ListBrandsUseCase,
  ListCategoriesUseCase,
  ListOfferBatchLinksUseCase,
  ListOfferDocumentsUseCase,
  ListOfferMediaUseCase,
  ListOffersUseCase,
  ListProductModelsUseCase,
} from './application/use-cases';
import { ProductRepository } from './infrastructure/persistence/product-repository';
import { ProductsRpcController } from './presentation/rpc/products.rpc-controller';

@Module({
  imports: [PrismaModule, MediaModule],
  controllers: [ProductsRpcController],
  providers: [
    ProductRepository,
    ListBrandsUseCase,
    CreateBrandUseCase,
    ListCategoriesUseCase,
    CreateCategoryUseCase,
    ListProductModelsUseCase,
    GetProductModelByIdUseCase,
    CreateProductModelUseCase,
    CreateOfferUseCase,
    AllocateOfferBatchesUseCase,
    GetOfferMediaUploadSignaturesUseCase,
    AddOfferMediaBatchUseCase,
    ListOfferMediaUseCase,
    ListOfferBatchLinksUseCase,
    GetOfferDocumentUploadSignaturesUseCase,
    AddOfferDocumentsBatchUseCase,
    ListOfferDocumentsUseCase,
    ListOffersUseCase,
    GetOfferByIdUseCase,
  ],
  exports: [
    ProductRepository,
    ListBrandsUseCase,
    CreateBrandUseCase,
    ListCategoriesUseCase,
    CreateCategoryUseCase,
    ListProductModelsUseCase,
    GetProductModelByIdUseCase,
    CreateProductModelUseCase,
    CreateOfferUseCase,
    AllocateOfferBatchesUseCase,
    GetOfferMediaUploadSignaturesUseCase,
    AddOfferMediaBatchUseCase,
    ListOfferMediaUseCase,
    ListOfferBatchLinksUseCase,
    GetOfferDocumentUploadSignaturesUseCase,
    AddOfferDocumentsBatchUseCase,
    ListOfferDocumentsUseCase,
    ListOffersUseCase,
    GetOfferByIdUseCase,
  ],
})
export class ProductsModule {}
