import { Module } from '@nestjs/common';
import { PrismaModule } from '@database/prisma/prisma.module';
import { MediaModule } from '@media';
import {
  AllocateOfferBatchesUseCase,
  AddFavoriteOfferUseCase,
  AddOfferDocumentsBatchUseCase,
  AddOfferMediaBatchUseCase,
  CreateBrandUseCase,
  CreateCategoryUseCase,
  CreateOfferUseCase,
  DeleteOfferDocumentUseCase,
  DeleteOfferMediaUseCase,
  GetOfferDocumentUploadSignaturesUseCase,
  GetOfferByIdUseCase,
  GetOfferMediaUploadSignaturesUseCase,
  ListFavoriteOffersUseCase,
  ListBrandsUseCase,
  ListCategoriesUseCase,
  ListOfferBatchLinksUseCase,
  ListOfferDocumentsUseCase,
  ListOfferMediaUseCase,
  ListOffersUseCase,
  ListShippingCarriersUseCase,
  RemoveFavoriteOfferUseCase,
  SetOfferPrimaryMediaUseCase,
  UpdateOfferUseCase,
} from './application/use-cases';
import { ProductRepository } from './infrastructure/persistence/product-repository';
import { ProductsRpcController } from './presentation/rpc/products.rpc-controller';

@Module({
  imports: [PrismaModule, MediaModule],
  controllers: [ProductsRpcController],
  providers: [
    ProductRepository,
    ListBrandsUseCase,
    CreateBrandUseCase,
    ListCategoriesUseCase,
    CreateCategoryUseCase,
    ListShippingCarriersUseCase,
    CreateOfferUseCase,
    UpdateOfferUseCase,
    AllocateOfferBatchesUseCase,
    GetOfferMediaUploadSignaturesUseCase,
    AddOfferMediaBatchUseCase,
    ListOfferMediaUseCase,
    DeleteOfferMediaUseCase,
    SetOfferPrimaryMediaUseCase,
    ListOfferBatchLinksUseCase,
    GetOfferDocumentUploadSignaturesUseCase,
    AddOfferDocumentsBatchUseCase,
    ListOfferDocumentsUseCase,
    DeleteOfferDocumentUseCase,
    ListOffersUseCase,
    GetOfferByIdUseCase,
    ListFavoriteOffersUseCase,
    AddFavoriteOfferUseCase,
    RemoveFavoriteOfferUseCase,
  ],
  exports: [
    ProductRepository,
    ListBrandsUseCase,
    CreateBrandUseCase,
    ListCategoriesUseCase,
    CreateCategoryUseCase,
    ListShippingCarriersUseCase,
    CreateOfferUseCase,
    UpdateOfferUseCase,
    AllocateOfferBatchesUseCase,
    GetOfferMediaUploadSignaturesUseCase,
    AddOfferMediaBatchUseCase,
    ListOfferMediaUseCase,
    DeleteOfferMediaUseCase,
    SetOfferPrimaryMediaUseCase,
    ListOfferBatchLinksUseCase,
    GetOfferDocumentUploadSignaturesUseCase,
    AddOfferDocumentsBatchUseCase,
    ListOfferDocumentsUseCase,
    DeleteOfferDocumentUseCase,
    ListOffersUseCase,
    GetOfferByIdUseCase,
    ListFavoriteOffersUseCase,
    AddFavoriteOfferUseCase,
    RemoveFavoriteOfferUseCase,
  ],
})
export class ProductsModule {}
