import { Module } from '@nestjs/common';
import { PrismaModule } from '@database/prisma/prisma.module';
import { WalletModule } from '@wallet/wallet.module';
import {
  ApproveAffiliateConversionUseCase,
  CreateAffiliateCodeUseCase,
  CreateAffiliatePayoutUseCase,
  CreateAffiliateProgramUseCase,
  GetAffiliateAccountSummaryUseCase,
  JoinAffiliateProgramUseCase,
  ListAffiliateCommissionsByAccountUseCase,
  ListAffiliateConversionsByAccountUseCase,
  ListAffiliateConversionsByProgramUseCase,
  ListAffiliateCodesByAccountUseCase,
  ListAffiliatePayoutsByAccountUseCase,
  ListAffiliatePayoutsByProgramUseCase,
  ListMyAffiliateAccountsUseCase,
  ListMyAffiliateProgramsUseCase,
  RejectAffiliateConversionUseCase,
  UpdateAffiliatePayoutStatusUseCase,
  SettleMatureAffiliateCommissionsUseCase,
  ResolveAffiliateAttributionUseCase,
  ListActiveAffiliateProgramsUseCase,
  ListAffiliateProgramMembersUseCase,
  ListSellerAffiliateProgramsUseCase,
  GetSellerAffiliateSummaryUseCase,
  UpdateAffiliateProgramUseCase,
  ListAffiliateProgramCommissionsUseCase,
} from './application/use-cases';
import { AffiliateRepository } from './infrastructure/persistence/affiliate.repository';
import { AffiliateRpcController } from './presentation/rpc/affiliate.rpc-controller';
import { AffiliateSettlementWorker } from './application/services/affiliate-settlement.worker';

@Module({
  imports: [PrismaModule, WalletModule],
  controllers: [AffiliateRpcController],
  providers: [
    AffiliateRepository,
    ApproveAffiliateConversionUseCase,
    CreateAffiliateProgramUseCase,
    CreateAffiliatePayoutUseCase,
    GetAffiliateAccountSummaryUseCase,
    ListMyAffiliateProgramsUseCase,
    JoinAffiliateProgramUseCase,
    ListAffiliateCommissionsByAccountUseCase,
    ListAffiliateConversionsByAccountUseCase,
    ListAffiliateConversionsByProgramUseCase,
    ListMyAffiliateAccountsUseCase,
    CreateAffiliateCodeUseCase,
    ListAffiliateCodesByAccountUseCase,
    ListAffiliatePayoutsByAccountUseCase,
    ListAffiliatePayoutsByProgramUseCase,
    RejectAffiliateConversionUseCase,
    UpdateAffiliatePayoutStatusUseCase,
    SettleMatureAffiliateCommissionsUseCase,
    ResolveAffiliateAttributionUseCase,
    ListActiveAffiliateProgramsUseCase,
    ListAffiliateProgramMembersUseCase,
    ListSellerAffiliateProgramsUseCase,
    GetSellerAffiliateSummaryUseCase,
    UpdateAffiliateProgramUseCase,
    ListAffiliateProgramCommissionsUseCase,
    AffiliateSettlementWorker,
  ],
  exports: [
    AffiliateRepository,
    ApproveAffiliateConversionUseCase,
    CreateAffiliateProgramUseCase,
    CreateAffiliatePayoutUseCase,
    GetAffiliateAccountSummaryUseCase,
    ListMyAffiliateProgramsUseCase,
    JoinAffiliateProgramUseCase,
    ListAffiliateCommissionsByAccountUseCase,
    ListAffiliateConversionsByAccountUseCase,
    ListAffiliateConversionsByProgramUseCase,
    ListMyAffiliateAccountsUseCase,
    CreateAffiliateCodeUseCase,
    ListAffiliateCodesByAccountUseCase,
    ListAffiliatePayoutsByAccountUseCase,
    ListAffiliatePayoutsByProgramUseCase,
    RejectAffiliateConversionUseCase,
    UpdateAffiliatePayoutStatusUseCase,
    SettleMatureAffiliateCommissionsUseCase,
    ResolveAffiliateAttributionUseCase,
    ListActiveAffiliateProgramsUseCase,
    ListAffiliateProgramMembersUseCase,
    ListSellerAffiliateProgramsUseCase,
    GetSellerAffiliateSummaryUseCase,
    UpdateAffiliateProgramUseCase,
    ListAffiliateProgramCommissionsUseCase,
  ],
})
export class AffiliateModule {}
