import { Module } from '@nestjs/common';
import { PrismaModule } from '@database/prisma/prisma.module';
import { MediaModule } from '@media';
import {
  CreateShopUseCase,
  GetBrandAuthorizationUploadSignaturesUseCase,
  GetAdminShopVerificationDetailUseCase,
  GetAdminShopVerificationSummaryUseCase,
  GetCategoryDocumentUploadSignaturesUseCase,
  GetShopVerificationSummaryUseCase,
  GetShopDocumentUploadSignaturesUseCase,
  GetShopByIdUseCase,
  ListBrandAuthorizationsUseCase,
  ListCategoryDocumentsUseCase,
  ListMyShopsUseCase,
  ListPendingVerificationShopsUseCase,
  ListShopDocumentsUseCase,
  ReviewBrandAuthorizationUseCase,
  ReviewShopCategoryUseCase,
  ReviewShopDocumentUseCase,
  SubmitBrandAuthorizationUseCase,
  SubmitCategoryDocumentsUseCase,
  SubmitShopDocumentsUseCase,
} from './application/use-cases';
import { ShopsRepository } from './infrastructure/persistence/shops.repository';
import { ShopsRpcController } from './presentation/rpc/shops.rpc-controller';

@Module({
  imports: [PrismaModule, MediaModule],
  controllers: [ShopsRpcController],
  providers: [
    ShopsRepository,
    CreateShopUseCase,
    GetBrandAuthorizationUploadSignaturesUseCase,
    GetAdminShopVerificationDetailUseCase,
    GetAdminShopVerificationSummaryUseCase,
    GetCategoryDocumentUploadSignaturesUseCase,
    GetShopVerificationSummaryUseCase,
    GetShopDocumentUploadSignaturesUseCase,
    GetShopByIdUseCase,
    ListBrandAuthorizationsUseCase,
    ListCategoryDocumentsUseCase,
    ListMyShopsUseCase,
    ListPendingVerificationShopsUseCase,
    ListShopDocumentsUseCase,
    ReviewBrandAuthorizationUseCase,
    ReviewShopCategoryUseCase,
    ReviewShopDocumentUseCase,
    SubmitBrandAuthorizationUseCase,
    SubmitCategoryDocumentsUseCase,
    SubmitShopDocumentsUseCase,
  ],
  exports: [
    ShopsRepository,
    CreateShopUseCase,
    GetBrandAuthorizationUploadSignaturesUseCase,
    GetAdminShopVerificationDetailUseCase,
    GetAdminShopVerificationSummaryUseCase,
    GetCategoryDocumentUploadSignaturesUseCase,
    GetShopVerificationSummaryUseCase,
    GetShopDocumentUploadSignaturesUseCase,
    GetShopByIdUseCase,
    ListBrandAuthorizationsUseCase,
    ListCategoryDocumentsUseCase,
    ListMyShopsUseCase,
    ListPendingVerificationShopsUseCase,
    ListShopDocumentsUseCase,
    ReviewBrandAuthorizationUseCase,
    ReviewShopCategoryUseCase,
    ReviewShopDocumentUseCase,
    SubmitBrandAuthorizationUseCase,
    SubmitCategoryDocumentsUseCase,
    SubmitShopDocumentsUseCase,
  ],
})
export class ShopsModule {}
