import { Module } from '@nestjs/common';
import { PrismaModule } from '@database/prisma/prisma.module';
import { MediaModule } from '@media';
import {
  CreateShopUseCase,
  UpdateShopProfileUseCase,
  UpdateShopRegistrationTypeUseCase,
  GetBrandAuthorizationUploadSignaturesUseCase,
  GetAdminShopVerificationDetailUseCase,
  GetAdminShopVerificationSummaryUseCase,
  GetPublicShopByOfferUseCase,
  GetShopVerificationSummaryUseCase,
  GetShopDocumentUploadSignaturesUseCase,
  GetShopByIdUseCase,
  ListAdminBrandAuthorizationsUseCase,
  ListBrandAuthorizationsUseCase,
  ListMyShopsUseCase,
  ListPendingVerificationShopsUseCase,
  ListPublicShopCategoriesUseCase,
  ListPublicShopsUseCase,
  ListShopDocumentRequirementsUseCase,
  ListShopDocumentsUseCase,
  ReviewBrandAuthorizationUseCase,
  ReviewShopDocumentUseCase,
  SubmitBrandAuthorizationUseCase,
  SubmitShopDocumentsUseCase,
} from './application/use-cases';
import { ShopsRepository } from './infrastructure/persistence/shops.repository';
import { ShopsRpcController } from './presentation/rpc/shops.rpc-controller';

@Module({
  imports: [PrismaModule, MediaModule],
  controllers: [ShopsRpcController],
  providers: [
    ShopsRepository,
    CreateShopUseCase,
    UpdateShopProfileUseCase,
    UpdateShopRegistrationTypeUseCase,
    GetBrandAuthorizationUploadSignaturesUseCase,
    GetAdminShopVerificationDetailUseCase,
    GetAdminShopVerificationSummaryUseCase,
    GetPublicShopByOfferUseCase,
    GetShopVerificationSummaryUseCase,
    GetShopDocumentUploadSignaturesUseCase,
    GetShopByIdUseCase,
    ListAdminBrandAuthorizationsUseCase,
    ListBrandAuthorizationsUseCase,
    ListMyShopsUseCase,
    ListPendingVerificationShopsUseCase,
    ListPublicShopCategoriesUseCase,
    ListPublicShopsUseCase,
    ListShopDocumentRequirementsUseCase,
    ListShopDocumentsUseCase,
    ReviewBrandAuthorizationUseCase,
    ReviewShopDocumentUseCase,
    SubmitBrandAuthorizationUseCase,
    SubmitShopDocumentsUseCase,
  ],
  exports: [
    ShopsRepository,
    CreateShopUseCase,
    UpdateShopProfileUseCase,
    UpdateShopRegistrationTypeUseCase,
    GetBrandAuthorizationUploadSignaturesUseCase,
    GetAdminShopVerificationDetailUseCase,
    GetAdminShopVerificationSummaryUseCase,
    GetPublicShopByOfferUseCase,
    GetShopVerificationSummaryUseCase,
    GetShopDocumentUploadSignaturesUseCase,
    GetShopByIdUseCase,
    ListAdminBrandAuthorizationsUseCase,
    ListBrandAuthorizationsUseCase,
    ListMyShopsUseCase,
    ListPendingVerificationShopsUseCase,
    ListPublicShopCategoriesUseCase,
    ListPublicShopsUseCase,
    ListShopDocumentRequirementsUseCase,
    ListShopDocumentsUseCase,
    ReviewBrandAuthorizationUseCase,
    ReviewShopDocumentUseCase,
    SubmitBrandAuthorizationUseCase,
    SubmitShopDocumentsUseCase,
  ],
})
export class ShopsModule {}
